CREATE TABLE ACCOUNT (
	ACC_ID    SERIAL   PRIMARY KEY,
	ACC_EMAIL  VARCHAR(100) NOT NULL,
	ACC_PASSWORD_HASH  TEXT NOT NULL -- convert this to hash, make a procedure
)

CREATE TABLE PROGRAM (
	PROGRAM_ID SERIAL PRIMARY KEY,
	PROGRAM_NAME TEXT NOT NULL,
	PROGRAM_ABV TEXT NOT NULL
)

CREATE TABLE COLLEGE (
	COLLEGE_ID SERIAL PRIMARY KEY,
	COLLEGE_NAME TEXT NOT NULL,
	COLLEGE_ABV TEXT NOT NULL
)

CREATE TABLE STUDENT (
	STUD_ID SERIAL PRIMARY KEY,
	STUD_ID_NUMBER CHAR(8) NOT NULL,
	STUD_FNAME VARCHAR(100) NOT NULL,
	STUD_MNAME VARCHAR(100) NOT NULL,
	STUD_LNAME VARCHAR(100) NOT NULL,
	STUD_YEAR  VARCHAR(1) NULL,
	STUD_isIRREGULAR BOOLEAN NOT NULL,
	STUD_CONTACT_NUMBER VARCHAR(11) NOT NULL,
	STUD_EMAIL VARCHAR(100) NOT NULL,
	STUD_BARANGAY TEXT NOT NULL,
	STUD_ADDRESS TEXT NOT NULL,
	STUD_EMERG_CONTACT_NAME TEXT NOT NULL,
	STUD_EMERG_CONTACT_NUM VARCHAR(11) NOT NULL,
	PROGRAM_ID INT NOT NULL,
	FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(PROGRAM_ID),
	COLLEGE_ID INT NOT NULL,
	FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE(COLLEGE_ID),
	ACC_ID INT NOT NULL,
	FOREIGN KEY (ACC_ID) REFERENCES ACCOUNT(ACC_ID)
)

CREATE USER admin_user WITH PASSWORD 'adminJuls';
GRANT ALL PRIVILEGES ON DATABASE "SCRaSMS" TO admin_user;

CREATE USER student_user WITH PASSWORD 'studentGroup5';
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO student_user;

ALTER TABLE ACCOUNT
ADD COLUMN ACC_ROLE VARCHAR(20),
ADD COLUMN ACC_isAPPROVED BOOLEAN DEFAULT FALSE;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO student_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO student_user; -- grants use on SERIAL

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE account TO admin_user; -- because I got [0]   File "C:\Users\Dell\Desktop\SCRaSMS\backend\admin_route.py", line 16, in submit_account_data
-- [0]     cur.execute("""
-- [0] psycopg2.errors.InsufficientPrivilege: permission denied for table account
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO admin_user; -- because I got [0]   File "C:\Users\Dell\Desktop\SCRaSMS\backend\admin_route.py", line 16, in submit_account_data
-- [0]     cur.execute("""
-- [0] psycopg2.errors.InsufficientPrivilege: permission denied for sequence account_acc_id_seq
-- [0]

CREATE TABLE ADMIN (
    ADMIN_ID SERIAL PRIMARY KEY,
    ADMIN_FNAME VARCHAR(100) NOT NULL,
    ADMIN_MNAME VARCHAR(100),
    ADMIN_LNAME VARCHAR(100) NOT NULL,
    ADMIN_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    ADMIN_CONTACT_NUMBER VARCHAR(11),
    ADMIN_ROLE VARCHAR(20) NOT NULL,
    ACC_ID INT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (ACC_ID) REFERENCES ACCOUNT(ACC_ID)
);

ALTER TABLE ADMIN 
DROP COLUMN ADMIN_ROLE;

ALTER TABLE STUDENT
ALTER COLUMN STUD_BARANGAY DROP NOT NULL,
ALTER COLUMN STUD_ADDRESS DROP NOT NULL,
ALTER COLUMN STUD_EMERG_CONTACT_NAME DROP NOT NULL,
ALTER COLUMN STUD_EMERG_CONTACT_NUM DROP NOT NULL;

ALTER TABLE STUDENT
DROP CONSTRAINT student_program_id_fkey,
DROP CONSTRAINT student_college_id_fkey;

ALTER TABLE STUDENT
RENAME COLUMN PROGRAM_ID TO STUD_PROGRAM;

ALTER TABLE STUDENT
RENAME COLUMN COLLEGE_ID TO STUD_COLLEGE;

ALTER TABLE STUDENT
ALTER COLUMN STUD_PROGRAM TYPE TEXT USING STUD_PROGRAM::TEXT;

ALTER TABLE STUDENT
ALTER COLUMN STUD_COLLEGE TYPE TEXT USING STUD_COLLEGE::TEXT;

TRUNCATE TABLE STUDENT, ACCOUNT RESTART IDENTITY CASCADE;


ALTER TABLE STUDENT
ALTER COLUMN STUD_CONTACT_NUMBER DROP NOT NULL;

CREATE TABLE STATUS (
	STAT_ID SERIAL PRIMARY KEY,
	STAT_TYPE TEXT NOT NULL,
	STAT_NOTES TEXT NULL,
	STAT_PHOTO BYTEA NULL,
	STUD_ID INT,
	FOREIGN KEY (STUD_ID) REFERENCES STUDENT (STUD_ID)
)

ALTER TABLE STATUS
ADD COLUMN STAT_CREATED_AT TIMESTAMP NOT NULL

ALTER TABLE STATUS
ADD COLUMN STAT_isRECENT BOOLEAN DEFAULT TRUE

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STATUS TO admin_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE status TO student_user;

SELECT 
    grantee, 
    privilege_type 
FROM 
    information_schema.table_privileges 
WHERE 
    table_name = 'status' AND grantee = 'admin_user';

